### ISSUE TITLE
Search confusion with shows containing another show name.

### ISSUE THREAD

**Issue by aTosser** [Jelomite/horrible-downloader#56]
When searching boku no hero academia - ikinokore! kesshi no survival kunren

The results returned are for "boku no hero academia"

Also affects subscription.
If you subscribe using a shorter term ex. "ikinokore" the config gets updated correctly but on execution results for the main show are returned.

I'll try to beat you to a fix, but I may not have time in the next couple of days.

**Comment by mtshrmn** [comment]
The problem lies in [here](https://github.com/mtshrmn/horrible-downloader/blob/3c459676af5655bb35dd024e16bd7fd055167136/HorribleDownloader/parser.py#L21)
```py
from rapidfuzz import process, fuzz
from HorribleDownloader import Parser

p = Parser()
process.extract("boku no hero academia - ikinokore! kesshi no survival kunren", p.shows.keys(), scorer=fuzz.token_set_ratio, limit=2)
# [('Boku no Hero Academia', 100.0), ('Boku no Hero Academia - Ikinokore! Kesshi no Survival Kunren', 100.0)]
```

For some reason, both `Boku no Hero Academia` and `Boku no Hero Academia - Ikinokore! Kesshi no Survival Kunren` have a score of 100. This is a continuation of #52, which was supposed to solve it. 

You can search for a better string matching algorithm, but the best solution is by implementing #43 which I don't have too much time to do (I've started the implementation on the [api-extend](https://github.com/mtshrmn/horrible-downloader/tree/api-extend) branch)

I'll try to continue working in it, but I'm not sure it'll happen soon.

**Comment by aTosser** [comment]
I'll take a look this weekend and see what I can work up with api-extend branch
